### ISSUE TITLE
Wiki issue

### ISSUE THREAD

**Issue by GiroudMathias** [iTexZoz/JetbrainIDE-CFX.RE#2]
Hi dude !

Good work for this !

But, the screens was not found on Wiki ;-)

https://github.com/iTexZoz/JetbrainIDE-CitizenFX/wiki/How-to-install-JetbrainIDE-CitizenFX-SDK-on-my-IDE-%3F

**Comment by ImBaphomettt** [comment]
Hello, 🤝 

thank you very much for reporting, the problem and linking to a task cron that deletes my screenshot every 3 months, I just solved the problem.

If you enjoy this project do not hesitate to put a small ⭐️ star, it motivates me for the future and my future opensource project! 

Sincerely Dylan Malandain.
