### ISSUE TITLE
Support with installation

### ISSUE THREAD

**Issue by Dreaming-Codes** [iTexZoz/JetbrainIDE-CFX.RE#3]
Where should I put the files in build?

**Comment by Naytoxp** [comment]
You have not to put any files in build, you just have to follow the instructions in the README.md file, and read the command prompt and chose which one you want to generate, then a folder will be created in "build"

**Comment by Dreaming-Codes** [comment]
okay, but once I have the files in build what should I do with them?

**Comment by xDope7137** [comment]
@Naytoxp I have same question. I have build and did everything. But how do I add it to my Intellij IDE or project?

There is no proper documentation on how to do it. Can you help and tell where should I add those files?

**Comment by Naytoxp** [comment]
Hello ! 

You have to add as a Project Library.
You have to use EmmyLua (I think so?)
Then you go to _File -> Project Structure_ (Ctrl+Alt+Shift+S).
You have to select _Libraries_ and add a new library using "Lua Zip" or something similar. And then select the folder of the file in build folder. 
Sometimes I have some issue loading them, try to play with them by using diffèrent Libs.

You can also search for "how to add a new library to project Idea" on Google.

I hope you will succeed to use this, cause it's awesome once setup.

Nb: I don't have looked much into how IDEA works, if I told things that aren't true or that you feel needs explanation, please feel free to correct me.

Have a nice day/night depending on where you are 😁

**Comment by xDope7137** [comment]
@Naytoxp Thanks for explaining that. But it totally went over my head. Can you please hop in a discord conversation and help me? I will only take few minutes.

xDope#2788 DMs are open

**Comment by Naytoxp** [comment]
Yes sure
